// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'src/infrastructure/database/prisma/schema.prisma',
  migrations: {
    path: 'src/infrastructure/database/prisma/migrations',
    seed: 'npx tsx src/infrastructure/database/prisma/seed.ts',
  },
  seed: 'npx tsx src/infrastructure/database/prisma/seed.ts', // Placé ici à la racine
  datasource: {
    url: process.env['MOVIES_DATABASE_URL'],
  },
});
